### ISSUE TITLE
Describe the release process

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-plus#6]
Now that the project is in pytest-dev, it would be nice to outline the release process somewhere. Nothing fancy, a small sequence of steps should be fine (see https://github.com/pytest-dev/pytest-xdist/blob/master/HOWTORELEASE.rst for en example).

**Comment by ssbarnea** [comment]
True. I will do it as it is highly automated and in fact relies only on "tag" greation on github, nothing more. Release notes are updated automatically by release-drafter.

The only issue is that there is no protection regarding checking validity of the tag (minor/major) so relies on knowledge of the one doing the tag but I do have plans to address this with https://github.com/pycontribs/tender/issues/15

I do plan to replace the current release-drafter with tender which will do far more than release-drafter but I will need few weeks to let it become ready for production use.

**Comment by nicoddemus** [comment]
Sounds good, thanks!
